/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{njk,md,html}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#fcf9f8",
        "secondary": "#7a5900",
        "surface-variant": "#e4e2e1",
        "on-tertiary-fixed": "#410002",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#23501e",
        "on-surface-variant": "#42493e",
        "surface-container-highest": "#e4e2e1",
        "primary": "#154212",
        "inverse-surface": "#303030",
        "on-tertiary": "#ffffff",
        "surface-container": "#f0eded",
        "on-primary-fixed": "#002201",
        "tertiary": "#790009",
        "on-primary": "#ffffff",
        "on-secondary-container": "#6b4d00",
        "on-surface": "#1b1c1c",
        "outline": "#72796e",
        "secondary-fixed-dim": "#fdbc13",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb4ab",
        "surface-bright": "#fcf9f8",
        "inverse-on-surface": "#f3f0f0",
        "surface-tint": "#3b6934",
        "background": "#fcf9f8",
        "secondary-fixed": "#ffdea3",
        "surface-container-low": "#f6f3f2",
        "surface-dim": "#dcd9d9",
        "primary-fixed": "#bcf0ae",
        "on-background": "#1b1c1c",
        "outline-variant": "#c2c9bb",
        "primary-container": "#2d5a27",
        "on-secondary-fixed-variant": "#5d4200",
        "on-secondary": "#ffffff",
        "tertiary-container": "#a50010",
        "on-secondary-fixed": "#261900",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#a1d494",
        "secondary-container": "#fdbc13",
        "on-primary-container": "#9dd090",
        "on-tertiary-fixed-variant": "#93000d",
        "surface-container-high": "#eae7e7",
        "error": "#ba1a1a",
        "on-tertiary-container": "#ffaea6",
        "inverse-primary": "#a1d494",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Epilogue", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
